//! Project scaffolding templates for `kmb init --template`.

use std::fmt;

/// Available project templates.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Template {
    /// Default template with minimal setup.
    Default,
    /// HIPAA-compliant healthcare schema.
    Healthcare,
    /// SEC/SOX/GLBA-compliant finance schema.
    Finance,
    /// Legal schema with chain of custody and eDiscovery.
    Legal,
    /// Multi-tenant isolation example.
    MultiTenant,
}

impl fmt::Display for Template {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Default => write!(f, "default"),
            Self::Healthcare => write!(f, "healthcare"),
            Self::Finance => write!(f, "finance"),
            Self::Legal => write!(f, "legal"),
            Self::MultiTenant => write!(f, "multi-tenant"),
        }
    }
}

impl std::str::FromStr for Template {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s.to_lowercase().as_str() {
            "default" => Ok(Self::Default),
            "healthcare" | "hipaa" => Ok(Self::Healthcare),
            "finance" | "fintech" => Ok(Self::Finance),
            "legal" => Ok(Self::Legal),
            "multi-tenant" | "multi_tenant" | "multitenant" => Ok(Self::MultiTenant),
            _ => Err(format!(
                "unknown template '{s}'. Available: default, healthcare, finance, legal, multi-tenant"
            )),
        }
    }
}

impl Template {
    /// Returns the initial migration SQL for the template.
    pub fn migration_sql(&self) -> Option<(&'static str, &'static str)> {
        match self {
            Self::Default => None,
            Self::Healthcare => Some(("001_healthcare_schema", HEALTHCARE_SQL)),
            Self::Finance => Some(("001_finance_schema", FINANCE_SQL)),
            Self::Legal => Some(("001_legal_schema", LEGAL_SQL)),
            Self::MultiTenant => Some(("001_multi_tenant_schema", MULTI_TENANT_SQL)),
        }
    }

    /// Returns a customized README for the template.
    pub fn readme(&self) -> &'static str {
        match self {
            Self::Default => DEFAULT_README,
            Self::Healthcare => HEALTHCARE_README,
            Self::Finance => FINANCE_README,
            Self::Legal => LEGAL_README,
            Self::MultiTenant => MULTI_TENANT_README,
        }
    }
}

// ---------------------------------------------------------------------------
// Healthcare template (HIPAA)
// ---------------------------------------------------------------------------

const HEALTHCARE_SQL: &str = r#"-- Healthcare Schema (HIPAA-compliant)
-- Generated by: kmb init --template healthcare

-- Up Migration

CREATE TABLE patients (
    id INTEGER PRIMARY KEY,
    mrn TEXT NOT NULL,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    date_of_birth TEXT NOT NULL,
    ssn TEXT,
    email TEXT,
    phone TEXT,
    address TEXT,
    insurance_id TEXT,
    created_at TEXT NOT NULL DEFAULT '2024-01-01T00:00:00Z',
    updated_at TEXT NOT NULL DEFAULT '2024-01-01T00:00:00Z'
);

CREATE TABLE encounters (
    id INTEGER PRIMARY KEY,
    patient_id INTEGER NOT NULL,
    provider_id INTEGER NOT NULL,
    encounter_type TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'active',
    chief_complaint TEXT,
    diagnosis_code TEXT,
    notes TEXT,
    encounter_date TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT '2024-01-01T00:00:00Z'
);

CREATE TABLE providers (
    id INTEGER PRIMARY KEY,
    npi TEXT NOT NULL,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    specialty TEXT NOT NULL,
    license_number TEXT NOT NULL,
    active INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE audit_log (
    id INTEGER PRIMARY KEY,
    user_id INTEGER NOT NULL,
    action TEXT NOT NULL,
    resource_type TEXT NOT NULL,
    resource_id TEXT NOT NULL,
    details TEXT,
    ip_address TEXT,
    timestamp TEXT NOT NULL DEFAULT '2024-01-01T00:00:00Z'
);

-- Down Migration

DROP TABLE audit_log;
DROP TABLE providers;
DROP TABLE encounters;
DROP TABLE patients;
"#;

const HEALTHCARE_README: &str = r"# Kimberlite Healthcare Project

HIPAA-compliant database for healthcare applications.

## Schema

- **patients** — Patient demographics (PHI fields: SSN, DOB, address)
- **encounters** — Clinical encounters linked to patients and providers
- **providers** — Healthcare provider registry with NPI numbers
- **audit_log** — Immutable audit trail for all data access

## Getting Started

```bash
kmb dev
```

Then connect with the REPL:

```bash
kmb repl --tenant 1
```

## Compliance

This template includes HIPAA-required audit logging and is designed for
use with Kimberlite's built-in data classification, masking, and access
control features.

See: https://kimberlite.dev/docs/concepts/compliance
";

// ---------------------------------------------------------------------------
// Finance template (SEC/SOX/GLBA)
// ---------------------------------------------------------------------------

const FINANCE_SQL: &str = r#"-- Finance Schema (SEC/SOX/GLBA-compliant)
-- Generated by: kmb init --template finance

-- Up Migration

CREATE TABLE accounts (
    id INTEGER PRIMARY KEY,
    account_number TEXT NOT NULL,
    account_type TEXT NOT NULL,
    owner_name TEXT NOT NULL,
    owner_ssn TEXT,
    balance_cents INTEGER NOT NULL DEFAULT 0,
    currency TEXT NOT NULL DEFAULT 'USD',
    status TEXT NOT NULL DEFAULT 'active',
    opened_at TEXT NOT NULL DEFAULT '2024-01-01T00:00:00Z',
    closed_at TEXT
);

CREATE TABLE trades (
    id INTEGER PRIMARY KEY,
    account_id INTEGER NOT NULL,
    symbol TEXT NOT NULL,
    side TEXT NOT NULL,
    quantity INTEGER NOT NULL,
    price_cents INTEGER NOT NULL,
    order_type TEXT NOT NULL DEFAULT 'market',
    status TEXT NOT NULL DEFAULT 'pending',
    executed_at TEXT,
    created_at TEXT NOT NULL DEFAULT '2024-01-01T00:00:00Z'
);

CREATE TABLE positions (
    id INTEGER PRIMARY KEY,
    account_id INTEGER NOT NULL,
    symbol TEXT NOT NULL,
    quantity INTEGER NOT NULL,
    avg_cost_cents INTEGER NOT NULL,
    current_value_cents INTEGER NOT NULL DEFAULT 0,
    updated_at TEXT NOT NULL DEFAULT '2024-01-01T00:00:00Z'
);

CREATE TABLE audit_log (
    id INTEGER PRIMARY KEY,
    user_id INTEGER NOT NULL,
    action TEXT NOT NULL,
    resource_type TEXT NOT NULL,
    resource_id TEXT NOT NULL,
    old_value TEXT,
    new_value TEXT,
    ip_address TEXT,
    timestamp TEXT NOT NULL DEFAULT '2024-01-01T00:00:00Z'
);

-- Down Migration

DROP TABLE audit_log;
DROP TABLE positions;
DROP TABLE trades;
DROP TABLE accounts;
"#;

const FINANCE_README: &str = r"# Kimberlite Finance Project

SEC/SOX/GLBA-compliant database for financial applications.

## Schema

- **accounts** — Customer accounts with balance tracking
- **trades** — Trade execution records with full audit trail
- **positions** — Portfolio positions derived from trade history
- **audit_log** — Immutable audit trail for regulatory compliance

## Getting Started

```bash
kmb dev
```

Then connect with the REPL:

```bash
kmb repl --tenant 1
```

## Compliance

This template supports SOX internal controls, SEC record-keeping
requirements, and GLBA safeguards for financial data protection.

See: https://kimberlite.dev/docs/concepts/compliance
";

// ---------------------------------------------------------------------------
// Legal template
// ---------------------------------------------------------------------------

const LEGAL_SQL: &str = r#"-- Legal Schema (Chain of Custody / eDiscovery)
-- Generated by: kmb init --template legal

-- Up Migration

CREATE TABLE cases (
    id INTEGER PRIMARY KEY,
    case_number TEXT NOT NULL,
    title TEXT NOT NULL,
    case_type TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'active',
    client_name TEXT NOT NULL,
    opposing_party TEXT,
    assigned_attorney TEXT NOT NULL,
    filed_date TEXT,
    created_at TEXT NOT NULL DEFAULT '2024-01-01T00:00:00Z'
);

CREATE TABLE evidence (
    id INTEGER PRIMARY KEY,
    case_id INTEGER NOT NULL,
    evidence_type TEXT NOT NULL,
    description TEXT NOT NULL,
    hash_sha256 TEXT NOT NULL,
    storage_location TEXT NOT NULL,
    collected_by TEXT NOT NULL,
    collected_at TEXT NOT NULL,
    chain_of_custody TEXT,
    created_at TEXT NOT NULL DEFAULT '2024-01-01T00:00:00Z'
);

CREATE TABLE legal_holds (
    id INTEGER PRIMARY KEY,
    case_id INTEGER NOT NULL,
    hold_name TEXT NOT NULL,
    custodian TEXT NOT NULL,
    scope TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'active',
    issued_at TEXT NOT NULL DEFAULT '2024-01-01T00:00:00Z',
    released_at TEXT
);

CREATE TABLE audit_log (
    id INTEGER PRIMARY KEY,
    user_id INTEGER NOT NULL,
    action TEXT NOT NULL,
    resource_type TEXT NOT NULL,
    resource_id TEXT NOT NULL,
    details TEXT,
    ip_address TEXT,
    timestamp TEXT NOT NULL DEFAULT '2024-01-01T00:00:00Z'
);

-- Down Migration

DROP TABLE audit_log;
DROP TABLE legal_holds;
DROP TABLE evidence;
DROP TABLE cases;
"#;

const LEGAL_README: &str = r"# Kimberlite Legal Project

Database for legal case management with chain of custody and eDiscovery support.

## Schema

- **cases** — Case tracking with status and party information
- **evidence** — Evidence records with SHA-256 hash verification
- **legal_holds** — Litigation hold management for eDiscovery
- **audit_log** — Immutable audit trail for all operations

## Getting Started

```bash
kmb dev
```

Then connect with the REPL:

```bash
kmb repl --tenant 1
```

## Compliance

This template supports legal hold requirements, chain of custody tracking,
eDiscovery obligations, and ABA ethics compliance.

See: https://kimberlite.dev/docs/concepts/compliance
";

// ---------------------------------------------------------------------------
// Multi-tenant template
// ---------------------------------------------------------------------------

const MULTI_TENANT_SQL: &str = r#"-- Multi-Tenant Schema
-- Generated by: kmb init --template multi-tenant

-- Up Migration

CREATE TABLE organizations (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT NOT NULL,
    plan TEXT NOT NULL DEFAULT 'free',
    max_users INTEGER NOT NULL DEFAULT 5,
    created_at TEXT NOT NULL DEFAULT '2024-01-01T00:00:00Z'
);

CREATE TABLE users (
    id INTEGER PRIMARY KEY,
    org_id INTEGER NOT NULL,
    email TEXT NOT NULL,
    name TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'user',
    active INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL DEFAULT '2024-01-01T00:00:00Z'
);

CREATE TABLE resources (
    id INTEGER PRIMARY KEY,
    org_id INTEGER NOT NULL,
    name TEXT NOT NULL,
    resource_type TEXT NOT NULL,
    data_class TEXT NOT NULL DEFAULT 'internal',
    created_by INTEGER NOT NULL,
    created_at TEXT NOT NULL DEFAULT '2024-01-01T00:00:00Z'
);

CREATE TABLE audit_log (
    id INTEGER PRIMARY KEY,
    org_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    action TEXT NOT NULL,
    resource_type TEXT NOT NULL,
    resource_id TEXT NOT NULL,
    details TEXT,
    timestamp TEXT NOT NULL DEFAULT '2024-01-01T00:00:00Z'
);

-- Down Migration

DROP TABLE audit_log;
DROP TABLE resources;
DROP TABLE users;
DROP TABLE organizations;
"#;

const MULTI_TENANT_README: &str = r"# Kimberlite Multi-Tenant Project

Multi-tenant application with organization-level isolation.

## Schema

- **organizations** — Tenant organizations with plan management
- **users** — Users scoped to organizations with role-based access
- **resources** — Tenant-scoped resources with data classification
- **audit_log** — Per-organization audit trail

## Getting Started

```bash
kmb dev
```

Then connect with the REPL:

```bash
kmb repl --tenant 1
```

## Tenant Isolation

Kimberlite provides hardware-level tenant isolation. Each tenant's data
is stored in separate streams with independent encryption keys and
access control policies.

See: https://kimberlite.dev/docs/concepts/architecture
";

// ---------------------------------------------------------------------------
// Default template
// ---------------------------------------------------------------------------

const DEFAULT_README: &str = r"# Kimberlite Project

Compliance-first database for regulated industries.

## Getting Started

Start the development server:

```bash
kmb dev
```

This will start both the database server and Studio UI.

## Commands

- `kmb dev` - Start development server (DB + Studio)
- `kmb repl --tenant 1` - Interactive SQL REPL
- `kmb migration create <name>` - Create a new migration
- `kmb tenant list` - List tenants
- `kmb config show` - Show current configuration

## Project Structure

```
.
├── kimberlite.toml          # Project configuration (git-tracked)
├── kimberlite.local.toml    # Local overrides (gitignored)
├── migrations/              # SQL migration files
└── .kimberlite/             # Local state (gitignored)
    ├── data/                # Database files
    ├── logs/                # Log files
    └── tmp/                 # Temporary files
```

## Documentation

Visit https://github.com/kimberlitedb/kimberlite for full documentation.
";
