#ifndef KIMBERLITE_FFI_H
#define KIMBERLITE_FFI_H

/* Generated with cbindgen:0.27.0 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/*
 Data classification for streams.
 */
typedef enum kmb_KmbDataClass {
    /*
     Protected Health Information (HIPAA-regulated)
     */
    KMB_KMB_DATA_CLASS_KMB_DATA_CLASS_PHI = 0,
    /*
     Non-PHI data
     */
    KMB_KMB_DATA_CLASS_KMB_DATA_CLASS_NON_PHI = 1,
    /*
     De-identified data
     */
    KMB_KMB_DATA_CLASS_KMB_DATA_CLASS_DEIDENTIFIED = 2,
} kmb_KmbDataClass;

/*
 Error codes returned by all FFI functions.

 Error code 0 (`KMB_OK`) indicates success.
 All other codes indicate various failure modes.
 */
typedef enum kmb_KmbError {
    /*
     Success (no error)
     */
    KMB_KMB_ERROR_KMB_OK = 0,
    /*
     NULL pointer passed where non-NULL required
     */
    KMB_KMB_ERROR_KMB_ERR_NULL_POINTER = 1,
    /*
     String is not valid UTF-8
     */
    KMB_KMB_ERROR_KMB_ERR_INVALID_UTF8 = 2,
    /*
     Failed to connect to server
     */
    KMB_KMB_ERROR_KMB_ERR_CONNECTION_FAILED = 3,
    /*
     Stream ID does not exist
     */
    KMB_KMB_ERROR_KMB_ERR_STREAM_NOT_FOUND = 4,
    /*
     Operation not permitted for this tenant
     */
    KMB_KMB_ERROR_KMB_ERR_PERMISSION_DENIED = 5,
    /*
     Invalid data class value
     */
    KMB_KMB_ERROR_KMB_ERR_INVALID_DATA_CLASS = 6,
    /*
     Offset is beyond stream end
     */
    KMB_KMB_ERROR_KMB_ERR_OFFSET_OUT_OF_RANGE = 7,
    /*
     SQL syntax error
     */
    KMB_KMB_ERROR_KMB_ERR_QUERY_SYNTAX = 8,
    /*
     Query execution error
     */
    KMB_KMB_ERROR_KMB_ERR_QUERY_EXECUTION = 9,
    /*
     Tenant ID does not exist
     */
    KMB_KMB_ERROR_KMB_ERR_TENANT_NOT_FOUND = 10,
    /*
     Authentication failed
     */
    KMB_KMB_ERROR_KMB_ERR_AUTH_FAILED = 11,
    /*
     Operation timed out
     */
    KMB_KMB_ERROR_KMB_ERR_TIMEOUT = 12,
    /*
     Internal server error
     */
    KMB_KMB_ERROR_KMB_ERR_INTERNAL = 13,
    /*
     No cluster replicas available
     */
    KMB_KMB_ERROR_KMB_ERR_CLUSTER_UNAVAILABLE = 14,
    /*
     Unknown error
     */
    KMB_KMB_ERROR_KMB_ERR_UNKNOWN = 15,
} kmb_KmbError;

/*
 Client connection configuration.
 */
typedef struct kmb_KmbClientConfig {
    /*
     Array of "host:port" strings (NULL-terminated)
     */
    const char *const *addresses;
    /*
     Number of addresses
     */
    uintptr_t address_count;
    /*
     Tenant ID
     */
    uint64_t tenant_id;
    /*
     Authentication token (NULL-terminated, may be empty)
     */
    const char *auth_token;
    /*
     Client name (e.g., "kimberlite-python")
     */
    const char *client_name;
    /*
     Client version (e.g., "0.1.0")
     */
    const char *client_version;
} kmb_KmbClientConfig;

/*
 Opaque handle to a client connection.

 Created by `kmb_client_connect()`, freed by `kmb_client_disconnect()`.
 */
typedef struct kmb_KmbClient {
    uint8_t _private[0];
} kmb_KmbClient;

/*
 Result from read_events operation.
 */
typedef struct kmb_KmbReadResult {
    /*
     Array of event data pointers
     */
    uint8_t **events;
    /*
     Parallel array of event lengths
     */
    uintptr_t *event_lengths;
    /*
     Number of events
     */
    uintptr_t event_count;
} kmb_KmbReadResult;

/*
 Connect to Kimberlite cluster.

 # Arguments
 - `config`: Connection configuration
 - `client_out`: Output parameter for client handle

 # Returns
 - `KMB_OK` on success
 - Error code on failure

 # Safety
 - `config` must be valid
 - All string pointers in config must be valid NULL-terminated C strings
 - Caller must call `kmb_client_disconnect()` to free client
 */
enum kmb_KmbError kmb_client_connect(const struct kmb_KmbClientConfig *config,
                                     struct kmb_KmbClient **client_out);

/*
 Disconnect from cluster and free client.

 # Arguments
 - `client`: Client handle from `kmb_client_connect()`

 # Safety
 - `client` must be a valid handle from `kmb_client_connect()`
 - After this call, `client` is invalid and must not be used
 */
void kmb_client_disconnect(struct kmb_KmbClient *client);

/*
 Create a new stream.

 # Arguments
 - `client`: Client handle
 - `name`: Stream name (NULL-terminated UTF-8)
 - `data_class`: Data classification
 - `stream_id_out`: Output parameter for stream ID

 # Returns
 - `KMB_OK` on success
 - Error code on failure

 # Safety
 - `client` must be valid
 - `name` must be valid NULL-terminated UTF-8 string
 - `stream_id_out` must be valid pointer
 */
enum kmb_KmbError kmb_client_create_stream(struct kmb_KmbClient *client,
                                           const char *name,
                                           enum kmb_KmbDataClass data_class,
                                           uint64_t *stream_id_out);

/*
 Append events to a stream.

 # Arguments
 - `client`: Client handle
 - `stream_id`: Stream ID
 - `events`: Array of byte buffers
 - `event_lengths`: Parallel array of buffer lengths
 - `event_count`: Number of events
 - `first_offset_out`: Output parameter for first offset

 # Returns
 - `KMB_OK` on success
 - Error code on failure

 # Safety
 - `client` must be valid
 - `events` must be array of `event_count` valid pointers
 - `event_lengths` must be array of `event_count` lengths
 - `first_offset_out` must be valid pointer
 */
enum kmb_KmbError kmb_client_append(struct kmb_KmbClient *client,
                                    uint64_t stream_id,
                                    const uint8_t *const *events,
                                    const uintptr_t *event_lengths,
                                    uintptr_t event_count,
                                    uint64_t *first_offset_out);

/*
 Read events from a stream.

 # Arguments
 - `client`: Client handle
 - `stream_id`: Stream ID
 - `from_offset`: Starting offset
 - `max_bytes`: Maximum bytes to read
 - `result_out`: Output parameter for read result

 # Returns
 - `KMB_OK` on success
 - Error code on failure

 # Safety
 - `client` must be valid
 - `result_out` must be valid pointer
 - Caller must call `kmb_read_result_free()` to free result
 */
enum kmb_KmbError kmb_client_read_events(struct kmb_KmbClient *client,
                                         uint64_t stream_id,
                                         uint64_t from_offset,
                                         uint64_t max_bytes,
                                         struct kmb_KmbReadResult **result_out);

/*
 Free read result.

 # Arguments
 - `result`: Result from `kmb_client_read_events()`

 # Safety
 - `result` must be a valid result from `kmb_client_read_events()`
 - After this call, `result` is invalid and must not be used
 */
void kmb_read_result_free(struct kmb_KmbReadResult *result);

/*
 Get human-readable error message for error code.

 # Arguments
 - `error`: Error code

 # Returns
 - Static NULL-terminated string (do not free)

 # Safety
 - Always safe to call
 - Returned string is valid for lifetime of program
 */
const char *kmb_error_message(enum kmb_KmbError error);

/*
 Check if an error code indicates a retryable failure.

 # Arguments
 - `error`: Error code

 # Returns
 - 1 if retryable, 0 otherwise

 # Safety
 - Always safe to call
 */
int kmb_error_is_retryable(enum kmb_KmbError error);

#endif  /* KIMBERLITE_FFI_H */
