#ifndef KIMBERLITE_FFI_H
#define KIMBERLITE_FFI_H

/* Generated with cbindgen:0.27.0 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#endif  /* KIMBERLITE_FFI_H */
