#ifndef KIMBERLITE_FFI_H
#define KIMBERLITE_FFI_H

/* Generated with cbindgen:0.29.2 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/*
 Error codes returned by all FFI functions.

 Error code 0 (`KMB_OK`) indicates success.
 All other codes indicate various failure modes.
 */
typedef enum kmb_KmbError {
    /*
     Success (no error)
     */
    KMB_KMB_ERROR_KMB_OK = 0,
    /*
     NULL pointer passed where non-NULL required
     */
    KMB_KMB_ERROR_KMB_ERR_NULL_POINTER = 1,
    /*
     String is not valid UTF-8
     */
    KMB_KMB_ERROR_KMB_ERR_INVALID_UTF8 = 2,
    /*
     Failed to connect to server
     */
    KMB_KMB_ERROR_KMB_ERR_CONNECTION_FAILED = 3,
    /*
     Stream ID does not exist
     */
    KMB_KMB_ERROR_KMB_ERR_STREAM_NOT_FOUND = 4,
    /*
     Operation not permitted for this tenant
     */
    KMB_KMB_ERROR_KMB_ERR_PERMISSION_DENIED = 5,
    /*
     Invalid data class value
     */
    KMB_KMB_ERROR_KMB_ERR_INVALID_DATA_CLASS = 6,
    /*
     Offset is beyond stream end
     */
    KMB_KMB_ERROR_KMB_ERR_OFFSET_OUT_OF_RANGE = 7,
    /*
     SQL syntax error
     */
    KMB_KMB_ERROR_KMB_ERR_QUERY_SYNTAX = 8,
    /*
     Query execution error
     */
    KMB_KMB_ERROR_KMB_ERR_QUERY_EXECUTION = 9,
    /*
     Tenant ID does not exist
     */
    KMB_KMB_ERROR_KMB_ERR_TENANT_NOT_FOUND = 10,
    /*
     Authentication failed
     */
    KMB_KMB_ERROR_KMB_ERR_AUTH_FAILED = 11,
    /*
     Operation timed out
     */
    KMB_KMB_ERROR_KMB_ERR_TIMEOUT = 12,
    /*
     Internal server error
     */
    KMB_KMB_ERROR_KMB_ERR_INTERNAL = 13,
    /*
     No cluster replicas available
     */
    KMB_KMB_ERROR_KMB_ERR_CLUSTER_UNAVAILABLE = 14,
    /*
     Unknown error
     */
    KMB_KMB_ERROR_KMB_ERR_UNKNOWN = 15,
} kmb_KmbError;

/*
 Reason a subscription was closed. Matches `SubscriptionCloseReason` in
 `kimberlite_wire`.
 */
typedef enum kmb_KmbSubscriptionCloseReason {
    KMB_KMB_SUBSCRIPTION_CLOSE_REASON_KMB_CLOSE_CLIENT_CANCELLED = 0,
    KMB_KMB_SUBSCRIPTION_CLOSE_REASON_KMB_CLOSE_SERVER_SHUTDOWN = 1,
    KMB_KMB_SUBSCRIPTION_CLOSE_REASON_KMB_CLOSE_STREAM_DELETED = 2,
    KMB_KMB_SUBSCRIPTION_CLOSE_REASON_KMB_CLOSE_BACKPRESSURE_TIMEOUT = 3,
    KMB_KMB_SUBSCRIPTION_CLOSE_REASON_KMB_CLOSE_PROTOCOL_ERROR = 4,
} kmb_KmbSubscriptionCloseReason;

/*
 Data classification for streams.

 Variants 0-2 are the original (Phi/NonPhi/Deidentified) ABI; variants 3-7
 extend the enum to cover every `kimberlite_types::DataClass` value.
 Old callers that only set 0/1/2 remain binary-compatible.
 */
typedef enum kmb_KmbDataClass {
    /*
     Protected Health Information (HIPAA-regulated)
     */
    KMB_KMB_DATA_CLASS_KMB_DATA_CLASS_PHI = 0,
    /*
     Non-PHI data (alias for Public).
     */
    KMB_KMB_DATA_CLASS_KMB_DATA_CLASS_NON_PHI = 1,
    /*
     De-identified data
     */
    KMB_KMB_DATA_CLASS_KMB_DATA_CLASS_DEIDENTIFIED = 2,
    /*
     Personally Identifiable Information (GDPR / CCPA)
     */
    KMB_KMB_DATA_CLASS_KMB_DATA_CLASS_PII = 3,
    /*
     Sensitive personal data (religion, health, sexual orientation, ...)
     */
    KMB_KMB_DATA_CLASS_KMB_DATA_CLASS_SENSITIVE = 4,
    /*
     Payment Card Industry data (PCI DSS)
     */
    KMB_KMB_DATA_CLASS_KMB_DATA_CLASS_PCI = 5,
    /*
     Financial records (SOX / GLBA)
     */
    KMB_KMB_DATA_CLASS_KMB_DATA_CLASS_FINANCIAL = 6,
    /*
     Confidential business data
     */
    KMB_KMB_DATA_CLASS_KMB_DATA_CLASS_CONFIDENTIAL = 7,
    /*
     Public / unclassified data
     */
    KMB_KMB_DATA_CLASS_KMB_DATA_CLASS_PUBLIC = 8,
} kmb_KmbDataClass;

/*
 Placement policy for a stream.

 `KmbPlacementCustom` reads the placement name from the `custom_region`
 argument of `kmb_client_create_stream_with_placement`.
 */
typedef enum kmb_KmbPlacement {
    /*
     Global replication across all regions (default).
     */
    KMB_KMB_PLACEMENT_KMB_PLACEMENT_GLOBAL = 0,
    /*
     US East (N. Virginia) — us-east-1
     */
    KMB_KMB_PLACEMENT_KMB_PLACEMENT_US_EAST1 = 1,
    /*
     Asia Pacific (Sydney) — ap-southeast-2
     */
    KMB_KMB_PLACEMENT_KMB_PLACEMENT_AP_SOUTHEAST2 = 2,
    /*
     Custom region identifier (string supplied separately).
     */
    KMB_KMB_PLACEMENT_KMB_PLACEMENT_CUSTOM = 3,
} kmb_KmbPlacement;

/*
 Query parameter type.
 */
typedef enum kmb_KmbQueryParamType {
    /*
     Null value
     */
    KMB_KMB_QUERY_PARAM_TYPE_KMB_PARAM_NULL = 0,
    /*
     64-bit integer
     */
    KMB_KMB_QUERY_PARAM_TYPE_KMB_PARAM_BIG_INT = 1,
    /*
     Text string
     */
    KMB_KMB_QUERY_PARAM_TYPE_KMB_PARAM_TEXT = 2,
    /*
     Boolean
     */
    KMB_KMB_QUERY_PARAM_TYPE_KMB_PARAM_BOOLEAN = 3,
    /*
     Timestamp (nanoseconds since epoch)
     */
    KMB_KMB_QUERY_PARAM_TYPE_KMB_PARAM_TIMESTAMP = 4,
} kmb_KmbQueryParamType;

/*
 Query value type (output from query).
 */
typedef enum kmb_KmbQueryValueType {
    /*
     Null value
     */
    KMB_KMB_QUERY_VALUE_TYPE_KMB_VALUE_NULL = 0,
    /*
     64-bit integer
     */
    KMB_KMB_QUERY_VALUE_TYPE_KMB_VALUE_BIG_INT = 1,
    /*
     Text string
     */
    KMB_KMB_QUERY_VALUE_TYPE_KMB_VALUE_TEXT = 2,
    /*
     Boolean
     */
    KMB_KMB_QUERY_VALUE_TYPE_KMB_VALUE_BOOLEAN = 3,
    /*
     Timestamp (nanoseconds since epoch)
     */
    KMB_KMB_QUERY_VALUE_TYPE_KMB_VALUE_TIMESTAMP = 4,
} kmb_KmbQueryValueType;

/*
 Pool configuration.

 `acquire_timeout_ms = 0` blocks forever.
 `idle_timeout_ms = 0` disables idle eviction.
 */
typedef struct kmb_KmbPoolConfig {
    /*
     Array of "host:port" strings (only the first is used).
     */
    const char *const *addresses;
    uintptr_t address_count;
    /*
     Tenant ID
     */
    uint64_t tenant_id;
    /*
     Authentication token (NULL-terminated, may be NULL or empty)
     */
    const char *auth_token;
    /*
     Maximum concurrent connections (must be > 0).
     */
    uintptr_t max_size;
    /*
     Milliseconds a caller will wait on `kmb_pool_acquire`; 0 = block forever.
     */
    uint64_t acquire_timeout_ms;
    /*
     Milliseconds an idle connection stays in the pool before eviction; 0 = never.
     */
    uint64_t idle_timeout_ms;
} kmb_KmbPoolConfig;

/*
 Opaque handle to a connection pool.

 Created with `kmb_pool_create()`, destroyed with `kmb_pool_destroy()`.
 Pools are thread-safe; a single handle can be shared across threads.
 */
typedef struct kmb_KmbPool {
    uint8_t _private[0];
} kmb_KmbPool;

/*
 Opaque handle to a pool-borrowed client. Dropping the handle returns the
 connection to the pool. Free with `kmb_pool_release()` or pass the handle
 to other `kmb_client_*` functions exactly like a regular `KmbClient`.
 */
typedef struct kmb_KmbPooledClient {
    uint8_t _private[0];
} kmb_KmbPooledClient;

/*
 Opaque handle to a client connection.

 Created by `kmb_client_connect()`, freed by `kmb_client_disconnect()`.
 */
typedef struct kmb_KmbClient {
    uint8_t _private[0];
} kmb_KmbClient;

/*
 Result from `kmb_subscribe`.
 */
typedef struct kmb_KmbSubscribeResult {
    uint64_t subscription_id;
    uint64_t start_offset;
    uint32_t initial_credits;
} kmb_KmbSubscribeResult;

/*
 A single event returned from `kmb_subscription_next`.

 The `data` pointer is owned by the library and remains valid until the
 next call on the same subscription. Copy the bytes if you need to
 retain them longer.
 */
typedef struct kmb_KmbSubscriptionEvent {
    uint64_t offset;
    uint8_t *data;
    uintptr_t data_len;
    /*
     Set to 1 when the subscription has closed — `data`/`data_len` are
     meaningless and `close_reason` carries the reason.
     */
    int closed;
    enum kmb_KmbSubscriptionCloseReason close_reason;
} kmb_KmbSubscriptionEvent;

/*
 Generic metadata listing — a JSON-encoded UTF-8 string owned by the library.

 Used for admin ops that return variable-length structured data
 (list_tables, tenant_list, api_key_list, etc.). Simpler than defining
 12 distinct repr(C) structs, and callers already have JSON parsers.

 Free via `kmb_admin_json_free`.
 */
typedef struct kmb_KmbAdminJson {
    /*
     NULL-terminated UTF-8 JSON. Owned — free with `kmb_admin_json_free`.
     */
    char *json;
} kmb_KmbAdminJson;

/*
 Client connection configuration.
 */
typedef struct kmb_KmbClientConfig {
    /*
     Array of "host:port" strings (NULL-terminated)
     */
    const char *const *addresses;
    /*
     Number of addresses
     */
    uintptr_t address_count;
    /*
     Tenant ID
     */
    uint64_t tenant_id;
    /*
     Authentication token (NULL-terminated, may be empty)
     */
    const char *auth_token;
    /*
     Client name (e.g., "kimberlite-python")
     */
    const char *client_name;
    /*
     Client version (e.g., "0.1.0")
     */
    const char *client_version;
} kmb_KmbClientConfig;

/*
 Query parameter value (input to query).
 */
typedef struct kmb_KmbQueryParam {
    /*
     Parameter type
     */
    enum kmb_KmbQueryParamType param_type;
    /*
     BigInt value (used when param_type == KmbParamBigInt)
     */
    int64_t bigint_val;
    /*
     Text value (NULL-terminated, used when param_type == KmbParamText)
     */
    const char *text_val;
    /*
     Boolean value (used when param_type == KmbParamBoolean)
     */
    int bool_val;
    /*
     Timestamp value (used when param_type == KmbParamTimestamp)
     */
    int64_t timestamp_val;
} kmb_KmbQueryParam;

/*
 Result of `kmb_client_execute()` — analogous to a DML acknowledgement.
 */
typedef struct kmb_KmbExecuteResult {
    /*
     Number of rows inserted / updated / deleted.
     */
    uint64_t rows_affected;
    /*
     Log offset at which the change was committed.
     */
    uint64_t log_offset;
} kmb_KmbExecuteResult;

/*
 Result from read_events operation.
 */
typedef struct kmb_KmbReadResult {
    /*
     Array of event data pointers
     */
    uint8_t **events;
    /*
     Parallel array of event lengths
     */
    uintptr_t *event_lengths;
    /*
     Number of events
     */
    uintptr_t event_count;
} kmb_KmbReadResult;

/*
 Query value (output from query).
 */
typedef struct kmb_KmbQueryValue {
    /*
     Value type
     */
    enum kmb_KmbQueryValueType value_type;
    /*
     BigInt value (used when value_type == KmbValueBigInt)
     */
    int64_t bigint_val;
    /*
     Text value (NULL-terminated, owned by result, used when value_type == KmbValueText)
     */
    char *text_val;
    /*
     Boolean value (used when value_type == KmbValueBoolean)
     */
    int bool_val;
    /*
     Timestamp value (used when value_type == KmbValueTimestamp)
     */
    int64_t timestamp_val;
} kmb_KmbQueryValue;

/*
 Query result (2D array of values).
 */
typedef struct kmb_KmbQueryResult {
    /*
     Array of column names (NULL-terminated C strings, owned by result)
     */
    char **columns;
    /*
     Number of columns
     */
    uintptr_t column_count;
    /*
     Array of rows (each row is an array of KmbQueryValue)
     */
    struct kmb_KmbQueryValue **rows;
    /*
     Array of row lengths (number of values in each row)
     */
    uintptr_t *row_lengths;
    /*
     Number of rows
     */
    uintptr_t row_count;
} kmb_KmbQueryResult;

/*
 Create a connection pool.

 # Safety
 - `config` must point to a valid `KmbPoolConfig`
 - `pool_out` must be non-null
 - Call `kmb_pool_destroy` to free the returned handle
 */
enum kmb_KmbError kmb_pool_create(const struct kmb_KmbPoolConfig *config,
                                  struct kmb_KmbPool **pool_out);

/*
 Acquire a client from the pool.

 The returned `KmbPooledClient` can be passed to `kmb_client_*` functions
 by casting via `kmb_pooled_client_as_client`. Release with
 `kmb_pool_release` to return it to the pool; `kmb_pool_discard` closes
 the underlying connection instead.

 # Safety
 - `pool` must be a valid handle from `kmb_pool_create`
 - `client_out` must be non-null
 */
enum kmb_KmbError kmb_pool_acquire(struct kmb_KmbPool *pool,
                                   struct kmb_KmbPooledClient **client_out);

/*
 Return a pooled client to the pool.

 # Safety
 - `client` must be a valid handle from `kmb_pool_acquire`
 - After this call the handle is invalid
 */
void kmb_pool_release(struct kmb_KmbPooledClient *client);

/*
 Discard a pooled client (drop the underlying TCP connection instead of
 returning it to the pool). Use after an unrecoverable protocol error.

 # Safety
 - `client` must be a valid handle from `kmb_pool_acquire`
 - After this call the handle is invalid
 */
void kmb_pool_discard(struct kmb_KmbPooledClient *client);

/*
 View a pooled-client handle as a regular `KmbClient` pointer.

 The returned pointer remains valid until the `KmbPooledClient` is
 released or discarded. Do NOT pass the returned pointer to
 `kmb_client_disconnect` — it does not own the connection.

 Internally the existing `kmb_client_*` functions interpret `*mut KmbClient`
 as `*mut ClientWrapper` where `ClientWrapper` has a single `Client` field
 at offset 0, so a `*mut Client` is ABI-compatible with `*mut KmbClient`.

 # Safety
 - `client` must be a valid handle from `kmb_pool_acquire`
 */
struct kmb_KmbClient *kmb_pooled_client_as_client(struct kmb_KmbPooledClient *client);

/*
 Current pool statistics. Writes `max_size`, `open`, `idle`, `in_use`,
 and `shutdown` (0/1) via out-parameters. Any out-pointer may be NULL
 to skip that field.

 # Safety
 - `pool` must be a valid handle from `kmb_pool_create`
 */
enum kmb_KmbError kmb_pool_stats(struct kmb_KmbPool *pool,
                                 uintptr_t *max_size_out,
                                 uintptr_t *open_out,
                                 uintptr_t *idle_out,
                                 uintptr_t *in_use_out,
                                 int *shutdown_out);

/*
 Shut down a pool. Idle connections close immediately; in-flight clients
 close when released. Subsequent acquires fail with
 `KMB_ERR_CONNECTION_FAILED`.

 # Safety
 - `pool` must be a valid handle from `kmb_pool_create`
 */
void kmb_pool_shutdown(struct kmb_KmbPool *pool);

/*
 Subscribe to real-time events on a stream.

 # Safety
 - `client` must be a valid handle from `kmb_client_connect` (or
   `kmb_pooled_client_as_client`)
 - `result_out` must be non-null
 */
enum kmb_KmbError kmb_subscribe(struct kmb_KmbClient *client,
                                uint64_t stream_id,
                                uint64_t from_offset,
                                uint32_t initial_credits,
                                struct kmb_KmbSubscribeResult *result_out);

/*
 Grant additional flow-control credits to an existing subscription.

 # Safety
 - `client` must be a valid handle
 - `new_balance_out` may be NULL if unused
 */
enum kmb_KmbError kmb_subscription_grant_credits(struct kmb_KmbClient *client,
                                                 uint64_t subscription_id,
                                                 uint32_t additional_credits,
                                                 uint32_t *new_balance_out);

/*
 Cancel a subscription.

 # Safety
 - `client` must be a valid handle
 */
enum kmb_KmbError kmb_subscription_unsubscribe(struct kmb_KmbClient *client,
                                               uint64_t subscription_id);

/*
 Block until the next event for `subscription_id` arrives (or the
 subscription closes).

 The returned `KmbSubscriptionEvent` owns heap-allocated data — free it
 via `kmb_subscription_event_free`.

 # Safety
 - `client` must be a valid handle
 - `event_out` must be non-null
 */
enum kmb_KmbError kmb_subscription_next(struct kmb_KmbClient *client,
                                        uint64_t subscription_id,
                                        struct kmb_KmbSubscriptionEvent *event_out);

/*
 Free a JSON string returned by an admin FFI call.

 # Safety
 - `result` must be a value returned by `kmb_admin_*` (or a zeroed struct)
 */
void kmb_admin_json_free(struct kmb_KmbAdminJson *result);

/*
 List tables in the caller's tenant. Returns `{"tables":[{"name":..,"column_count":..}]}`.

 # Safety
 - `client` must be valid
 - `result_out` must be non-null; caller frees via `kmb_admin_json_free`
 */
enum kmb_KmbError kmb_admin_list_tables(struct kmb_KmbClient *client,
                                        struct kmb_KmbAdminJson *result_out);

/*
 Describe a table's columns. Returns `{"table_name":..,"columns":[...]}`.

 # Safety
 - `client`, `table_name`, `result_out` must be non-null
 - `table_name` must be NULL-terminated UTF-8
 */
enum kmb_KmbError kmb_admin_describe_table(struct kmb_KmbClient *client,
                                           const char *table_name,
                                           struct kmb_KmbAdminJson *result_out);

/*
 List indexes on a table. Returns `{"indexes":[{"name":..,"columns":[...]}]}`.

 # Safety
 - `client`, `table_name`, `result_out` must be non-null
 */
enum kmb_KmbError kmb_admin_list_indexes(struct kmb_KmbClient *client,
                                         const char *table_name,
                                         struct kmb_KmbAdminJson *result_out);

/*
 Register a tenant. Returns `{"tenant":{...},"created":true|false}`.

 # Safety
 - `client` and `result_out` must be non-null
 - `name` may be NULL for an unnamed registration
 */
enum kmb_KmbError kmb_admin_tenant_create(struct kmb_KmbClient *client,
                                          uint64_t tenant_id,
                                          const char *name,
                                          struct kmb_KmbAdminJson *result_out);

/*
 List all registered tenants. Returns `{"tenants":[...]}`.

 # Safety
 - `client` and `result_out` must be non-null
 */
enum kmb_KmbError kmb_admin_tenant_list(struct kmb_KmbClient *client,
                                        struct kmb_KmbAdminJson *result_out);

/*
 Delete a tenant. Returns `{"deleted":bool,"tables_dropped":n}`.

 # Safety
 - `client` and `result_out` must be non-null
 */
enum kmb_KmbError kmb_admin_tenant_delete(struct kmb_KmbClient *client,
                                          uint64_t tenant_id,
                                          struct kmb_KmbAdminJson *result_out);

/*
 Fetch a tenant summary. Returns `{"tenant":{...}}`.

 # Safety
 - `client` and `result_out` must be non-null
 */
enum kmb_KmbError kmb_admin_tenant_get(struct kmb_KmbClient *client,
                                       uint64_t tenant_id,
                                       struct kmb_KmbAdminJson *result_out);

/*
 Issue a new API key. Returns `{"key":"...","info":{...}}`.

 The plaintext `key` is returned exactly once — persist it immediately.

 # Safety
 - `client`, `subject`, and `result_out` must be non-null
 - `roles_json` must be a NULL-terminated UTF-8 JSON array of strings
 */
enum kmb_KmbError kmb_admin_api_key_register(struct kmb_KmbClient *client,
                                             const char *subject,
                                             uint64_t tenant_id,
                                             const char *roles_json,
                                             uint64_t expires_at_nanos,
                                             struct kmb_KmbAdminJson *result_out);

/*
 Revoke an API key by plaintext. Returns `{"revoked":bool}`.

 # Safety
 - `client`, `key`, and `result_out` must be non-null
 */
enum kmb_KmbError kmb_admin_api_key_revoke(struct kmb_KmbClient *client,
                                           const char *key,
                                           struct kmb_KmbAdminJson *result_out);

/*
 List API-key metadata. `tenant_id == 0` means "all tenants". Returns
 `{"keys":[{...}]}`. Never includes plaintext.

 # Safety
 - `client` and `result_out` must be non-null
 */
enum kmb_KmbError kmb_admin_api_key_list(struct kmb_KmbClient *client,
                                         uint64_t tenant_id,
                                         struct kmb_KmbAdminJson *result_out);

/*
 Atomically rotate an API key. Returns `{"new_key":"...","info":{...}}`.

 # Safety
 - `client`, `old_key`, and `result_out` must be non-null
 */
enum kmb_KmbError kmb_admin_api_key_rotate(struct kmb_KmbClient *client,
                                           const char *old_key,
                                           struct kmb_KmbAdminJson *result_out);

/*
 Get canonical server info. Returns
 `{"build_version":..,"protocol_version":..,"capabilities":[...],"uptime_secs":..,"cluster_mode":"Standalone|Clustered","tenant_count":..}`.

 # Safety
 - `client` and `result_out` must be non-null
 */
enum kmb_KmbError kmb_admin_server_info(struct kmb_KmbClient *client,
                                        struct kmb_KmbAdminJson *result_out);

/*
 Grant consent. `purpose` is a string matching the `ConsentPurpose` enum.
 `basis_json` is an optional null-pointer or UTF-8 JSON payload of shape
 `{"article":"Consent","justification":"..."}` — added in wire v4 (v0.6.0)
 to thread the GDPR Article 6(1) lawful basis onto the grant. Unknown
 articles return `KmbErrInternal`; callers should pass `NULL` to preserve
 legacy behaviour.
 */
enum kmb_KmbError kmb_compliance_consent_grant(struct kmb_KmbClient *client,
                                               const char *subject_id,
                                               const char *purpose,
                                               const char *basis_json,
                                               struct kmb_KmbAdminJson *result_out);

/*
 Withdraw consent by ID.
 */
enum kmb_KmbError kmb_compliance_consent_withdraw(struct kmb_KmbClient *client,
                                                  const char *consent_id,
                                                  struct kmb_KmbAdminJson *result_out);

/*
 Check consent. Returns `{"is_valid": bool}`.
 */
enum kmb_KmbError kmb_compliance_consent_check(struct kmb_KmbClient *client,
                                               const char *subject_id,
                                               const char *purpose,
                                               struct kmb_KmbAdminJson *result_out);

/*
 List consent records. `valid_only = 1` hides withdrawn/expired.
 */
enum kmb_KmbError kmb_compliance_consent_list(struct kmb_KmbClient *client,
                                              const char *subject_id,
                                              int valid_only,
                                              struct kmb_KmbAdminJson *result_out);

/*
 Request erasure for a subject. Returns the request record.
 */
enum kmb_KmbError kmb_compliance_erasure_request(struct kmb_KmbClient *client,
                                                 const char *subject_id,
                                                 struct kmb_KmbAdminJson *result_out);

/*
 Fetch current status of an erasure request.
 */
enum kmb_KmbError kmb_compliance_erasure_status(struct kmb_KmbClient *client,
                                                const char *request_id,
                                                struct kmb_KmbAdminJson *result_out);

/*
 Complete an erasure request (returns the audit record).
 */
enum kmb_KmbError kmb_compliance_erasure_complete(struct kmb_KmbClient *client,
                                                  const char *request_id,
                                                  struct kmb_KmbAdminJson *result_out);

/*
 Mark an erasure request as exempt under GDPR Art. 17(3). `basis` is one of
 `"LegalObligation" | "PublicHealth" | "Archiving" | "LegalClaims"`.
 */
enum kmb_KmbError kmb_compliance_erasure_exempt(struct kmb_KmbClient *client,
                                                const char *request_id,
                                                const char *basis,
                                                struct kmb_KmbAdminJson *result_out);

/*
 Record that one stream has been erased as part of an ongoing
 erasure request. Mirrors
 `Client::erasure_mark_stream_erased` for SDKs that consume the
 C ABI (Python, C, etc.).

 `request_id` is the UUID string returned by
 `kmb_compliance_erasure_request`. `stream_id` is the 64-bit stream
 handle. `records_erased` is the count that was erased on this
 stream.

 Returns the updated `ErasureRequestInfo` as JSON in `result_out`.

 # Safety
 - `client` must be a valid `*mut KmbClient` returned by
   `kmb_client_connect`
 - `request_id` must be a valid NUL-terminated UTF-8 string
 - `result_out` must point to a writable `KmbAdminJson`
 */
enum kmb_KmbError kmb_compliance_erasure_mark_stream_erased(struct kmb_KmbClient *client,
                                                            const char *request_id,
                                                            uint64_t stream_id,
                                                            uint64_t records_erased,
                                                            struct kmb_KmbAdminJson *result_out);

/*
 AUDIT-2026-04 S3.6 — query the compliance audit log.

 All filter arguments are nullable strings or sentinel `0`
 values. `subject_id`, `action_type`, `actor` of NULL mean
 "don't filter on this field". `time_from_nanos` /
 `time_to_nanos` of 0 mean "unbounded in that direction".
 `limit` of 0 uses the server's default.

 Returns a JSON object `{ "events": [...] }` where each event
 is rendered by `audit_event_to_json`.

 # Safety
 - `client` must be a valid `KmbClient`.
 - Every non-NULL string pointer must be a valid NUL-terminated
   UTF-8 string.
 - `result_out` must point to a writable `KmbAdminJson`.
 */
enum kmb_KmbError kmb_compliance_audit_query(struct kmb_KmbClient *client,
                                             const char *subject_id,
                                             const char *action_type,
                                             uint64_t time_from_nanos,
                                             uint64_t time_to_nanos,
                                             const char *actor,
                                             uint32_t limit,
                                             struct kmb_KmbAdminJson *result_out);

/*
 AUDIT-2026-04 S3.6 — GDPR Article 20 portability export.

 `format` is `"Json"` or `"Csv"`. `stream_ids_json` is a JSON
 array of u64 stream IDs, or NULL for "every stream".
 `max_records_per_stream` of 0 uses the server's default.

 Returns the `PortabilityExportInfo` as JSON in `result_out`.

 # Safety
 - `client` must be a valid `KmbClient`.
 - `subject_id`, `requester_id`, `format` must be
   NUL-terminated UTF-8 strings.
 - `stream_ids_json` may be NULL; otherwise it must be a
   NUL-terminated UTF-8 JSON array of u64.
 */
enum kmb_KmbError kmb_compliance_export_subject(struct kmb_KmbClient *client,
                                                const char *subject_id,
                                                const char *requester_id,
                                                const char *format,
                                                const char *stream_ids_json,
                                                uint64_t max_records_per_stream,
                                                struct kmb_KmbAdminJson *result_out);

/*
 List every audited erasure request for the tenant.
 */
enum kmb_KmbError kmb_compliance_erasure_list(struct kmb_KmbClient *client,
                                              struct kmb_KmbAdminJson *result_out);

/*
 Free the heap-allocated `data` inside a `KmbSubscriptionEvent`.

 Safe to call with a closed event (`closed == 1`, `data == NULL`).

 # Safety
 - `event` must either be a valid event returned by `kmb_subscription_next`
   or a freshly-zeroed struct
 */
void kmb_subscription_event_free(struct kmb_KmbSubscriptionEvent *event);

/*
 Destroy a pool, freeing all remaining resources. Implicitly calls shutdown.

 # Safety
 - `pool` must be a valid handle from `kmb_pool_create`
 - After this call the handle is invalid
 */
void kmb_pool_destroy(struct kmb_KmbPool *pool);

/*
 Connect to Kimberlite cluster.

 # Arguments
 - `config`: Connection configuration
 - `client_out`: Output parameter for client handle

 # Returns
 - `KMB_OK` on success
 - Error code on failure

 # Safety
 - `config` must be valid
 - All string pointers in config must be valid NULL-terminated C strings
 - Caller must call `kmb_client_disconnect()` to free client
 */
enum kmb_KmbError kmb_client_connect(const struct kmb_KmbClientConfig *config,
                                     struct kmb_KmbClient **client_out);

/*
 Disconnect from cluster and free client.

 # Arguments
 - `client`: Client handle from `kmb_client_connect()`

 # Safety
 - `client` must be a valid handle from `kmb_client_connect()`
 - After this call, `client` is invalid and must not be used
 */
void kmb_client_disconnect(struct kmb_KmbClient *client);

/*
 Create a new stream.

 # Arguments
 - `client`: Client handle
 - `name`: Stream name (NULL-terminated UTF-8)
 - `data_class`: Data classification
 - `stream_id_out`: Output parameter for stream ID

 # Returns
 - `KMB_OK` on success
 - Error code on failure

 # Safety
 - `client` must be valid
 - `name` must be valid NULL-terminated UTF-8 string
 - `stream_id_out` must be valid pointer
 */
enum kmb_KmbError kmb_client_create_stream(struct kmb_KmbClient *client,
                                           const char *name,
                                           enum kmb_KmbDataClass data_class,
                                           uint64_t *stream_id_out);

/*
 Create a new stream with a specific placement policy.

 # Arguments
 - `client`: Client handle
 - `name`: Stream name (NULL-terminated UTF-8)
 - `data_class`: Data classification
 - `placement`: Geographic placement policy
 - `custom_region`: Custom region identifier (only read when
   `placement == KmbPlacementCustom`; may be NULL otherwise)
 - `stream_id_out`: Output parameter for stream ID

 # Returns
 - `KMB_OK` on success
 - Error code on failure

 # Safety
 - `client` must be valid
 - `name` must be valid NULL-terminated UTF-8 string
 - If `placement == KmbPlacementCustom`, `custom_region` must be valid
   NULL-terminated UTF-8
 - `stream_id_out` must be valid pointer
 */
enum kmb_KmbError kmb_client_create_stream_with_placement(struct kmb_KmbClient *client,
                                                          const char *name,
                                                          enum kmb_KmbDataClass data_class,
                                                          enum kmb_KmbPlacement placement,
                                                          const char *custom_region,
                                                          uint64_t *stream_id_out);

/*
 Returns the tenant ID this client is connected as.

 # Safety
 - `client` must be a valid handle
 - `tenant_id_out` must be a valid pointer
 */
enum kmb_KmbError kmb_client_tenant_id(struct kmb_KmbClient *client, uint64_t *tenant_id_out);

/*
 Returns the wire request ID of the most recently sent request.

 Useful for correlating client-side logs with server-side tracing output.
 Writes `0` if no request has been sent yet.

 # Safety
 - `client` must be a valid handle
 - `request_id_out` must be a valid pointer
 */
enum kmb_KmbError kmb_client_last_request_id(struct kmb_KmbClient *client,
                                             uint64_t *request_id_out);

/*
 Execute a DML or DDL statement (INSERT / UPDATE / DELETE / CREATE / ALTER).

 # Arguments
 - `client`: Client handle
 - `sql`: SQL statement (NULL-terminated UTF-8)
 - `params`: Array of query parameters (may be NULL if `param_count == 0`)
 - `param_count`: Number of parameters
 - `result_out`: Output parameter for rows-affected and log offset

 # Safety
 - `client` must be valid
 - `sql` must be valid NULL-terminated UTF-8 string
 - `params` must be array of `param_count` valid parameters (or NULL if
   `param_count == 0`)
 - `result_out` must be valid pointer
 */
enum kmb_KmbError kmb_client_execute(struct kmb_KmbClient *client,
                                     const char *sql,
                                     const struct kmb_KmbQueryParam *params,
                                     uintptr_t param_count,
                                     struct kmb_KmbExecuteResult *result_out);

/*
 Append events to a stream.

 # Arguments
 - `client`: Client handle
 - `stream_id`: Stream ID
 - `expected_offset`: Expected current stream offset (optimistic concurrency)
 - `events`: Array of byte buffers
 - `event_lengths`: Parallel array of buffer lengths
 - `event_count`: Number of events
 - `first_offset_out`: Output parameter for first offset

 # Returns
 - `KMB_OK` on success
 - Error code on failure

 # Safety
 - `client` must be valid
 - `events` must be array of `event_count` valid pointers
 - `event_lengths` must be array of `event_count` lengths
 - `first_offset_out` must be valid pointer
 */
enum kmb_KmbError kmb_client_append(struct kmb_KmbClient *client,
                                    uint64_t stream_id,
                                    uint64_t expected_offset,
                                    const uint8_t *const *events,
                                    const uintptr_t *event_lengths,
                                    uintptr_t event_count,
                                    uint64_t *first_offset_out);

/*
 Read events from a stream.

 # Arguments
 - `client`: Client handle
 - `stream_id`: Stream ID
 - `from_offset`: Starting offset
 - `max_bytes`: Maximum bytes to read
 - `result_out`: Output parameter for read result

 # Returns
 - `KMB_OK` on success
 - Error code on failure

 # Safety
 - `client` must be valid
 - `result_out` must be valid pointer
 - Caller must call `kmb_read_result_free()` to free result
 */
enum kmb_KmbError kmb_client_read_events(struct kmb_KmbClient *client,
                                         uint64_t stream_id,
                                         uint64_t from_offset,
                                         uint64_t max_bytes,
                                         struct kmb_KmbReadResult **result_out);

/*
 Free read result.

 # Arguments
 - `result`: Result from `kmb_client_read_events()`

 # Safety
 - `result` must be a valid result from `kmb_client_read_events()`
 - After this call, `result` is invalid and must not be used
 */
void kmb_read_result_free(struct kmb_KmbReadResult *result);

/*
 Execute a SQL query against current state.

 # Arguments
 - `client`: Client handle
 - `sql`: SQL query string (NULL-terminated UTF-8)
 - `params`: Array of query parameters (may be NULL if param_count == 0)
 - `param_count`: Number of parameters
 - `result_out`: Output parameter for query result

 # Returns
 - `KMB_OK` on success
 - Error code on failure

 # Safety
 - `client` must be valid
 - `sql` must be valid NULL-terminated UTF-8 string
 - `params` must be array of `param_count` valid parameters (or NULL if param_count == 0)
 - `result_out` must be valid pointer
 - Caller must call `kmb_query_result_free()` to free result
 */
enum kmb_KmbError kmb_client_query(struct kmb_KmbClient *client,
                                   const char *sql,
                                   const struct kmb_KmbQueryParam *params,
                                   uintptr_t param_count,
                                   struct kmb_KmbQueryResult **result_out);

/*
 Execute a SQL query at a specific log position (point-in-time query).

 # Arguments
 - `client`: Client handle
 - `sql`: SQL query string (NULL-terminated UTF-8)
 - `params`: Array of query parameters (may be NULL if param_count == 0)
 - `param_count`: Number of parameters
 - `position`: Log position (offset) to query at
 - `result_out`: Output parameter for query result

 # Returns
 - `KMB_OK` on success
 - Error code on failure

 # Safety
 - `client` must be valid
 - `sql` must be valid NULL-terminated UTF-8 string
 - `params` must be array of `param_count` valid parameters (or NULL if param_count == 0)
 - `result_out` must be valid pointer
 - Caller must call `kmb_query_result_free()` to free result
 */
enum kmb_KmbError kmb_client_query_at(struct kmb_KmbClient *client,
                                      const char *sql,
                                      const struct kmb_KmbQueryParam *params,
                                      uintptr_t param_count,
                                      uint64_t position,
                                      struct kmb_KmbQueryResult **result_out);

/*
 Free query result.

 # Arguments
 - `result`: Result from `kmb_client_query()` or `kmb_client_query_at()`

 # Safety
 - `result` must be a valid result from `kmb_client_query()` or `kmb_client_query_at()`
 - After this call, `result` is invalid and must not be used
 */
void kmb_query_result_free(struct kmb_KmbQueryResult *result);

/*
 Get human-readable error message for error code.

 # Arguments
 - `error`: Error code

 # Returns
 - Static NULL-terminated string (do not free)

 # Safety
 - Always safe to call
 - Returned string is valid for lifetime of program
 */
const char *kmb_error_message(enum kmb_KmbError error);

/*
 Check if an error code indicates a retryable failure.

 # Arguments
 - `error`: Error code

 # Returns
 - 1 if retryable, 0 otherwise

 # Safety
 - Always safe to call
 */
int kmb_error_is_retryable(enum kmb_KmbError error);

/*
 Set the audit context on the current thread. All subsequent FFI
 client calls on this thread attach the context to their outgoing
 wire [`Request.audit`][kimberlite_wire::Request::audit] so the
 server-side compliance ledger records client attribution.

 Language bindings are expected to call this before each SDK method
 when an ambient audit context exists in the caller's language-level
 carrier (Python `contextvars`, TS `AsyncLocalStorage`, Go
 `context.Context`) and call [`kmb_audit_clear`] after.

 All arguments are optional — passing `NULL` for any pointer leaves
 that field unset.

 # Safety
 Each non-NULL pointer must be a valid NUL-terminated UTF-8 string.
 */
enum kmb_KmbError kmb_audit_set(const char *actor,
                                const char *reason,
                                const char *correlation_id,
                                const char *idempotency_key);

/*
 Clear the FFI audit context on the current thread. Called by the
 language binding after an SDK method returns, so subsequent calls
 don't pick up stale attribution.
 */
enum kmb_KmbError kmb_audit_clear(void);

#endif  /* KIMBERLITE_FFI_H */
